<a href="https://colab.research.google.com/github/ADITI9981/Deep_Learning/blob/main/Amazon_reviews_from_the_Cell_Phones_%26_Accessories(Word2Vec_gensim).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import gensim
import pandas as pd

In [3]:
df = pd.read_json("Cell_Phones_and_Accessories_5.json", lines=True)
df.head()

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
0,A30TL5EWN6DFXT,120401325X,christina,"[0, 0]",They look good and stick good! I just don't li...,4,Looks Good,1400630400,"05 21, 2014"
1,ASY55RVNIL0UD,120401325X,emily l.,"[0, 0]",These stickers work like the review says they ...,5,Really great product.,1389657600,"01 14, 2014"
2,A2TMXE2AFO7ONB,120401325X,Erica,"[0, 0]",These are awesome and make my phone look so st...,5,LOVE LOVE LOVE,1403740800,"06 26, 2014"
3,AWJ0WZQYMYFQ4,120401325X,JM,"[4, 4]",Item arrived in great time and was in perfect ...,4,Cute!,1382313600,"10 21, 2013"
4,ATX7CZYFXI1KW,120401325X,patrice m rogoza,"[2, 3]","awesome! stays on, and looks great. can be use...",5,leopard home button sticker for iphone 4s,1359849600,"02 3, 2013"

In [5]:
df.shape

(194439, 9)

In [6]:
df.reviewText[0]

"They look good and stick good! I just don't like the rounded shape because I was always bumping it and Siri kept popping up and it was irritating. I just won't buy a product like this again"

In [7]:

review_text = df.reviewText.apply(gensim.utils.simple_preprocess)
review_text

0         [they, look, good, and, stick, good, just, don...
1         [these, stickers, work, like, the, review, say...
2         [these, are, awesome, and, make, my, phone, lo...
3         [item, arrived, in, great, time, and, was, in,...
4         [awesome, stays, on, and, looks, great, can, b...
                                ...
194434    [works, great, just, like, my, original, one, ...
194435    [great, product, great, packaging, high, quali...
194436    [this, is, great, cable, just, as, good, as, t...
194437    [really, like, it, becasue, it, works, well, w...
194438    [product, as, described, have, wasted, lot, of...
Name: reviewText, Length: 194439, dtype: object

In [8]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2,
    workers=4,
)

In [9]:
model.build_vocab(review_text,progress_per=1000)

In [10]:
model.epochs

5

In [11]:
model.train(review_text, total_examples=model.corpus_count, epochs=model.epochs)

(61503310, 83868975)

In [12]:
model.save("./word2vec-amazon-cell-accessories-reviews-short.model")

In [13]:
model.wv.most_similar("bad")

[('terrible', 0.7017059326171875),
 ('shabby', 0.6406075954437256),
 ('horrible', 0.6006448864936829),
 ('good', 0.5821259617805481),
 ('crappy', 0.5524893403053284),
 ('funny', 0.5494611859321594),
 ('awful', 0.5474185347557068),
 ('legit', 0.5367722511291504),
 ('okay', 0.5215029120445251),
 ('weird', 0.5119648575782776)]

In [14]:
model.wv.similarity(w1="cheap", w2="inexpensive")

0.52642447

In [15]:
model.wv.similarity(w1="shabby", w2="horrible")

0.17882389