<a href="https://colab.research.google.com/github/ADITI9981/Deep_Learning/blob/main/Gradient_Decent_For_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
df=pd.read_csv("insurance_d.csv")
df.head()

   age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [ ]:
df.shape

(28, 3)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2,random_state=20)

In [ ]:
len(x_train)

22

In [ ]:
x_train_scaled=x_train.copy()
x_train_scaled['age']=x_train_scaled['age']/100

x_test_scaled=x_test.copy()
x_test_scaled['age']=x_test_scaled['age']/100

In [ ]:
x_train_scaled

     age  affordibility
18  0.19              0
25  0.54              1
23  0.45              1
22  0.40              1
21  0.26              0
5   0.56              1
24  0.50              1
19  0.18              1
14  0.49              1
17  0.58              1
6   0.55              0
16  0.25              0
8   0.62              1
0   0.22              1
2   0.47              1
7   0.60              0
11  0.28              1
20  0.21              1
9   0.61              1
15  0.55              1
26  0.23              1
3   0.52              0

In [ ]:
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')

])
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(x_train_scaled,y_train,epochs=5000)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Streaming output truncated to the last 5000 lines.
Epoch 2501/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6818 - loss: 0.4883
Epoch 2502/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6818 - loss: 0.4883
Epoch 2503/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6818 - loss: 0.4883
Epoch 2504/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6818 - loss: 0.4882
Epoch 2505/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.6818 - loss: 0.4882
Epoch 2506/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6818 - loss: 0.4881
Epoch 2507/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.6818 - loss: 0.4881
Epoch 2508/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6818 - loss: 0.4881
Epoch 2509/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6818 - loss: 0.4880
Epoch 2510/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.6818 - loss: 0.4880
Epoch 2511/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6818 - loss: 0.4880
Epoch 2512/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.6818 - loss: 0.4879
Epoch 2513/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6818 - loss: 0.4879
Epoch 2514/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.6818 - loss: 0.4878
Epoch 2515/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - accuracy: 0.6818 - loss: 0.4878
Epoch 2516/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.6818 - loss: 0.4878
Epoch 2517/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.6818 - loss: 0.4877
Epoch 2518/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.6818 - loss: 0.4877
Epoch 2519/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.6818 - loss: 0.4877
Epoch 2520/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 191ms/step - accuracy: 0.6818 - loss: 0.4876
Epoch 2521/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - accuracy: 0.6818 - loss: 0.4876
Epoch 2522/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 180ms/step - accuracy: 0.6818 - loss: 0.4876
Epoch 2523/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 252ms/step - accuracy: 0.6818 - loss: 0.4875
Epoch 2524/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 0.6818 - loss: 0.4875
Epoch 2525/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.6818 - loss: 0.4874
Epoch 2526/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.6818 - loss: 0.4874
Epoch 2527/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - accuracy: 0.6818 - loss: 0.4874
Epoch 2528/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.6818 - loss: 0.4873
Epoch 2529/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - accuracy: 0.6818 - loss: 0.4873
Epoch 2530/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.6818 - loss: 0.4873
Epoch 2531/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.6818 - loss: 0.4872
Epoch 2532/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.6818 - loss: 0.4872
Epoch 2533/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - accuracy: 0.6818 - loss: 0.4871
Epoch 2534/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.6818 - loss: 0.4871
Epoch 2535/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - accuracy: 0.6818 - loss: 0.4871
Epoch 2536/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - accuracy: 0.6818 - loss: 0.4870
Epoch 2537/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - accuracy: 0.6818 - loss: 0.4870
Epoch 2538/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.6818 - loss: 0.4870
Epoch 2539/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6818 - loss: 0.4869
Epoch 2540/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6818 - loss: 0.4869
Epoch 2541/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.6818 - loss: 0.4868
Epoch 2542/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6818 - loss: 0.4868
Epoch 2543/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.6818 - loss: 0.4868
Epoch 2544/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 0.6818 - loss: 0.4867
Epoch 2545/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 0.6818 - loss: 0.4867
Epoch 2546/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6818 - loss: 0.4867
Epoch 2547/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - accuracy: 0.6818 - loss: 0.4866
Epoch 2548/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.6818 - loss: 0.4866
Epoch 2549/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 0.6818 - loss: 0.4866
Epoch 2550/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.6818 - loss: 0.4865
Epoch 2551/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.6818 - loss: 0.4865
Epoch 2552/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6818 - loss: 0.4864
Epoch 2553/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - accuracy: 0.6818 - loss: 0.4864
Epoch 2554/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 246ms/step - accuracy: 0.6818 - loss: 0.4864
Epoch 2555/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.6818 - loss: 0.4863
Epoch 2556/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.6818 - loss: 0.4863
Epoch 2557/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6818 - loss: 0.4863
Epoch 2558/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6818 - loss: 0.4862
Epoch 2559/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6818 - loss: 0.4862
Epoch 2560/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6818 - loss: 0.4862
Epoch 2561/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.6818 - loss: 0.4861
Epoch 2562/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6818 - loss: 0.4861
Epoch 2563/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6818 - loss: 0.4860
Epoch 2564/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6818 - loss: 0.4860
Epoch 2565/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.6818 - loss: 0.4860
Epoch 2566/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6818 - loss: 0.4859
Epoch 2567/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6818 - loss: 0.4859
Epoch 2568/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6818 - loss: 0.4859
Epoch 2569/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.6818 - loss: 0.4858
Epoch 2570/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.6818 - loss: 0.4858
Epoch 2571/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6818 - loss: 0.4857
Epoch 2572/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.6818 - loss: 0.4857
Epoch 2573/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6818 - loss: 0.4857
Epoch 2574/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.6818 - loss: 0.4856
Epoch 2575/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.6818 - loss: 0.4856
Epoch 2576/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step - accuracy: 0.6818 - loss: 0.4856
Epoch 2577/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.6818 - loss: 0.4855
Epoch 2578/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6818 - loss: 0.4855
Epoch 2579/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6818 - loss: 0.4855
Epoch 2580/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6818 - loss: 0.4854
Epoch 2581/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.6818 - loss: 0.4854
Epoch 2582/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6818 - loss: 0.4853
Epoch 2583/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.6818 - loss: 0.4853
Epoch 2584/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6818 - loss: 0.4853
Epoch 2585/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.6818 - loss: 0.4852
Epoch 2586/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.6818 - loss: 0.4852
Epoch 2587/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6818 - loss: 0.4852
Epoch 2588/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6818 - loss: 0.4851
Epoch 2589/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6818 - loss: 0.4851
Epoch 2590/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6818 - loss: 0.4851
Epoch 2591/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6818 - loss: 0.4850
Epoch 2592/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6818 - loss: 0.4850
Epoch 2593/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.6818 - loss: 0.4849
Epoch 2594/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6818 - loss: 0.4849
Epoch 2595/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6818 - loss: 0.4849
Epoch 2596/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6818 - loss: 0.4848
Epoch 2597/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.6818 - loss: 0.4848
Epoch 2598/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - accuracy: 0.6818 - loss: 0.4848
Epoch 2599/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.6818 - loss: 0.4847
Epoch 2600/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - accuracy: 0.6818 - loss: 0.4847
Epoch 2601/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - accuracy: 0.6818 - loss: 0.4847
Epoch 2602/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 0.6818 - loss: 0.4846
Epoch 2603/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6818 - loss: 0.4846
Epoch 2604/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.6818 - loss: 0.4845
Epoch 2605/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6818 - loss: 0.4845
Epoch 2606/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6818 - loss: 0.4845
Epoch 2607/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 194ms/step - accuracy: 0.6818 - loss: 0.4844
Epoch 2608/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6818 - loss: 0.4844
Epoch 2609/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.6818 - loss: 0.4844
Epoch 2610/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - accuracy: 0.6818 - loss: 0.4843
Epoch 2611/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 0.6818 - loss: 0.4843
Epoch 2612/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.6818 - loss: 0.4843
Epoch 2613/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.6818 - loss: 0.4842
Epoch 2614/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.6818 - loss: 0.4842
Epoch 2615/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.6818 - loss: 0.4841
Epoch 2616/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6818 - loss: 0.4841
Epoch 2617/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6818 - loss: 0.4841
Epoch 2618/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - accuracy: 0.6818 - loss: 0.4840
Epoch 2619/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6818 - loss: 0.4840
Epoch 2620/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.6818 - loss: 0.4840
Epoch 2621/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.6818 - loss: 0.4839
Epoch 2622/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6818 - loss: 0.4839
Epoch 2623/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.6818 - loss: 0.4839
Epoch 2624/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6818 - loss: 0.4838
Epoch 2625/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6818 - loss: 0.4838
Epoch 2626/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - accuracy: 0.6818 - loss: 0.4838
Epoch 2627/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.6818 - loss: 0.4837
Epoch 2628/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6818 - loss: 0.4837
Epoch 2629/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6818 - loss: 0.4836
Epoch 2630/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.6818 - loss: 0.4836
Epoch 2631/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.6818 - loss: 0.4836
Epoch 2632/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6818 - loss: 0.4835
Epoch 2633/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.6818 - loss: 0.4835
Epoch 2634/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6818 - loss: 0.4835
Epoch 2635/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6818 - loss: 0.4834
Epoch 2636/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.6818 - loss: 0.4834
Epoch 2637/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.6818 - loss: 0.4834
Epoch 2638/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6818 - loss: 0.4833
Epoch 2639/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6818 - loss: 0.4833
Epoch 2640/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6818 - loss: 0.4832
Epoch 2641/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.6818 - loss: 0.4832
Epoch 2642/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6818 - loss: 0.4832
Epoch 2643/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6818 - loss: 0.4831
Epoch 2644/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.6818 - loss: 0.4831
Epoch 2645/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.6818 - loss: 0.4831
Epoch 2646/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 0.6818 - loss: 0.4830
Epoch 2647/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 0.6818 - loss: 0.4830
Epoch 2648/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6818 - loss: 0.4830
Epoch 2649/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step - accuracy: 0.6818 - loss: 0.4829
Epoch 2650/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 0.6818 - loss: 0.4829
Epoch 2651/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.6818 - loss: 0.4829
Epoch 2652/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - accuracy: 0.6818 - loss: 0.4828
Epoch 2653/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - accuracy: 0.6818 - loss: 0.4828
Epoch 2654/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.6818 - loss: 0.4827
Epoch 2655/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.6818 - loss: 0.4827
Epoch 2656/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.6818 - loss: 0.4827
Epoch 2657/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 0.6818 - loss: 0.4826
Epoch 2658/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step - accuracy: 0.6818 - loss: 0.4826
Epoch 2659/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 253ms/step - accuracy: 0.6818 - loss: 0.4826
Epoch 2660/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.6818 - loss: 0.4825
Epoch 2661/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.6818 - loss: 0.4825
Epoch 2662/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - accuracy: 0.6818 - loss: 0.4825
Epoch 2663/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.6818 - loss: 0.4824
Epoch 2664/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 0.6818 - loss: 0.4824
Epoch 2665/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.6818 - loss: 0.4824
Epoch 2666/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - accuracy: 0.6818 - loss: 0.4823
Epoch 2667/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.6818 - loss: 0.4823
Epoch 2668/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - accuracy: 0.6818 - loss: 0.4822
Epoch 2669/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 0.6818 - loss: 0.4822
Epoch 2670/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.6818 - loss: 0.4822
Epoch 2671/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.6818 - loss: 0.4821
Epoch 2672/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6818 - loss: 0.4821
Epoch 2673/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6818 - loss: 0.4821
Epoch 2674/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6818 - loss: 0.4820
Epoch 2675/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6818 - loss: 0.4820
Epoch 2676/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.6818 - loss: 0.4820
Epoch 2677/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6818 - loss: 0.4819
Epoch 2678/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6818 - loss: 0.4819
Epoch 2679/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 0.6818 - loss: 0.4819
Epoch 2680/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.6818 - loss: 0.4818
Epoch 2681/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6818 - loss: 0.4818
Epoch 2682/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6818 - loss: 0.4818
Epoch 2683/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.6818 - loss: 0.4817
Epoch 2684/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6818 - loss: 0.4817
Epoch 2685/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6818 - loss: 0.4816
Epoch 2686/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.6818 - loss: 0.4816
Epoch 2687/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6818 - loss: 0.4816
Epoch 2688/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6818 - loss: 0.4815
Epoch 2689/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.6818 - loss: 0.4815
Epoch 2690/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6818 - loss: 0.4815
Epoch 2691/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.6818 - loss: 0.4814
Epoch 2692/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6818 - loss: 0.4814
Epoch 2693/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step - accuracy: 0.6818 - loss: 0.4814
Epoch 2694/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 195ms/step - accuracy: 0.6818 - loss: 0.4813
Epoch 2695/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.6818 - loss: 0.4813
Epoch 2696/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6818 - loss: 0.4813
Epoch 2697/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6818 - loss: 0.4812
Epoch 2698/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6818 - loss: 0.4812
Epoch 2699/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6818 - loss: 0.4811
Epoch 2700/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.6818 - loss: 0.4811
Epoch 2701/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6818 - loss: 0.4811
Epoch 2702/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6818 - loss: 0.4810
Epoch 2703/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6818 - loss: 0.4810
Epoch 2704/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.6818 - loss: 0.4810
Epoch 2705/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6818 - loss: 0.4809
Epoch 2706/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6818 - loss: 0.4809
Epoch 2707/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.6818 - loss: 0.4809
Epoch 2708/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6818 - loss: 0.4808
Epoch 2709/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6818 - loss: 0.4808
Epoch 2710/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6818 - loss: 0.4808
Epoch 2711/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.6818 - loss: 0.4807
Epoch 2712/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.6818 - loss: 0.4807
Epoch 2713/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6818 - loss: 0.4807
Epoch 2714/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6818 - loss: 0.4806
Epoch 2715/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.6818 - loss: 0.4806
Epoch 2716/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6818 - loss: 0.4806
Epoch 2717/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6818 - loss: 0.4805
Epoch 2718/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6818 - loss: 0.4805
Epoch 2719/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.6818 - loss: 0.4804
Epoch 2720/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.6818 - loss: 0.4804
Epoch 2721/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6818 - loss: 0.4804
Epoch 2722/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6818 - loss: 0.4803
Epoch 2723/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6818 - loss: 0.4803
Epoch 2724/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.6818 - loss: 0.4803
Epoch 2725/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6818 - loss: 0.4802
Epoch 2726/5000

In [11]:
x_test_scaled

     age  affordibility
13  0.29              0
4   0.46              1
1   0.25              0
10  0.18              1
27  0.46              1
12  0.27              0

In [12]:
model.predict(x_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

array([[0.2111646 ],
       [0.7487071 ],
       [0.17427608],
       [0.36073586],
       [0.7487071 ],
       [0.19204609]], dtype=float32)

In [13]:
coef,intercept=model.get_weights()
coef,intercept

(array([[5.942501 ],
        [1.3994231]], dtype=float32),
 array([-3.041245], dtype=float32))

In [15]:
def sigmoid(x):
  import math
  return 1/(1+math.exp(-x))
sigmoid(18)

0.9999999847700205

In [16]:
def prediction_function(age,affordability):
  weighted_sum=coef[0]*age+coef[1]*affordability+intercept
  return sigmoid(weighted_sum)
prediction_function(0.47,1)

<ipython-input-15-c72387dc9e07>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))

0.7597215571264704

In [24]:
def log_loss(y_true,y_prediction):
  epsilon=1e-15
  y_predicted_new=[max(i,epsilon) for i in y_prediction]
  y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
  y_predicted_new=np.array(y_predicted_new)
  return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [25]:
def sigmoid_numpy(x):
  return 1/(1+np.exp(-x))
sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [41]:
class myNN:
  def __init__(self):
    self.w1=1
    self.w2=1
    self.bias=0

  def fit(self,x,y,epochs,loss_threshold):
    self.w1,self.w2,self.bias = self.gradient_descent(x['age'],x['affordibility'],y,epochs,loss_threshold)

  def predict(self,x_test):
    weighted_sum=self.w1*x_test['age']+self.w2*x_test['affordibility']+self.bias
    return sigmoid_numpy(weighted_sum)

  def gradient_descent(self,age,affordability,y_true,epochs,loss_thresold):
      w1=w2=1
      bias=0
      rate=0.5
      n=len(age)
      for i in range(epochs):
        weighted_sum=w1*age+w2*affordability+bias
        y_predicted=sigmoid_numpy(weighted_sum)
        loss=log_loss(y_true,y_predicted)
        w1d=(1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
        w2d=(1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true))
        bias_d=np.mean(y_predicted-y_true)
        w1=w1-rate*w1d
        w2=w2-rate*w2d
        bias=bias-rate*bias_d

        if i%50==0:
             print(f'epoch:{i},w1:{w1},w2:{w2},bias:{bias},loss:{loss}')

        if(loss<=loss_thresold):
           break
      return w1,w2,bias

In [42]:
gradient_descent(x_train_scaled['age'],x_train_scaled['affordibility'],y_train,1000,0.4631)

epoch:0,w1:0.9899044631276738,w2:0.9569405919425348,bias:-0.07899372792977674,loss:0.645879853336323
epoch:1,w1:0.9839956437241003,w2:0.9213120476683795,bias:-0.14783282323721283,loss:0.6306399722613678
epoch:2,w1:0.9818392584739325,w2:0.8924082047006104,bias:-0.20758236411882589,loss:0.6194338742775531
epoch:3,w1:0.9829714996091098,w2:0.8694378697530099,bias:-0.25936841626475815,loss:0.6112638943448379
epoch:4,w1:0.9869327312511998,w2:0.8515941187585563,bias:-0.3042992643556669,loss:0.6053096946136317
epoch:5,w1:0.9932909005876579,w2:0.8381042430709594,bias:-0.3434115278383518,loss:0.6009323224120783
epoch:6,w1:1.0016552381106507,w2:0.828260552915365,bias:-0.3776393247774238,loss:0.5976547897595172
epoch:7,w1:1.0116822714409655,w2:0.821435592496283,bias:-0.407801431258409,loss:0.5951326106822025
epoch:8,w1:1.0230764951373805,w2:0.817086248135435,bias:-0.4346007971785253,loss:0.5931233031450338
epoch:9,w1:1.035587744835964,w2:0.81475080344,bias:-0.45863157249275605,loss:0.5914595419655675
epoch:10,w1:1.0490068190601034,w2:0.8140420606621083,bias:-0.48039003679846487,loss:0.5900276180279254
epoch:11,w1:1.063160397557054,w2:0.814638685901002,bias:-0.5002870066433593,loss:0.5887511602169311
epoch:12,w1:1.0779059086335554,w2:0.8162761471511589,bias:-0.5186602284957997,loss:0.5875793312482571
epoch:13,w1:1.0931267138078111,w2:0.8187380401668405,bias:-0.5357859276221825,loss:0.5864785161508326
epoch:14,w1:1.1087277895907102,w2:0.8218482112513408,bias:-0.5518891185293225,loss:0.5854265946732674
epoch:15,w1:1.124631969055576,w2:0.8254638427858639,bias:-0.5671525507498613,loss:0.5844090570268506
epoch:16,w1:1.140776737854453,w2:0.8294695233405666,bias:-0.5817243176380682,loss:0.583416401285316
epoch:17,w1:1.1571115433309356,w2:0.8337722455412421,bias:-0.5957242359547112,loss:0.5824424054360666
epoch:18,w1:1.173595559217973,w2:0.838297237153964,bias:-0.6092491387184844,loss:0.5814829881352781
epoch:19,w1:1.1901958439624118,w2:0.8429845176603405,bias:-0.6223772319339945,loss:0.5805354616130546
epoch:20,w1:1.2068858327622727,w2:0.8477860732850141,bias:-0.6351716593987157,loss:0.5795980437518939
epoch:21,w1:1.2236441086994994,w2:0.852663551349663,bias:-0.6476834062495108,loss:0.5786695404278469
epoch:22,w1:1.2404534049652964,w2:0.8575863859445239,bias:-0.6599536556253518,loss:0.5777491391912415
epoch:23,w1:1.2572997970029374,w2:0.862530278899649,bias:-0.6720156962797899,loss:0.5768362754987927
epoch:24,w1:1.274172049845058,w2:0.8674759716296097,bias:-0.6838964634801555,loss:0.5759305460941266
epoch:25,w1:1.2910610917207912,w2:0.8724082539852971,bias:-0.695617781680075,loss:0.5750316529652152
epoch:26,w1:1.3079595900556729,w2:0.8773151655218285,bias:-0.7071973654389628,loss:0.5741393671009098
epoch:27,w1:1.3248616102877653,w2:0.8821873525435406,bias:-0.7186496248534567,loss:0.5732535050530254
epoch:28,w1:1.3417623415322706,w2:0.887017550990217,bias:-0.7299863132148803,loss:0.5723739137739107
epoch:29,w1:1.3586578761220462,w2:0.8918001708107622,bias:-0.7412170475196129,loss:0.5715004607990399
epoch:30,w1:1.3755450325169716,w2:0.8965309620773784,bias:-0.7523497266310488,loss:0.5706330278807683
epoch:31,w1:1.3924212130921656,w2:0.9012067468697169,bias:-0.7633908671272466,loss:0.5697715068501906
epoch:32,w1:1.4092842899574674,w2:0.9058252040383221,bias:-0.7743458729908477,loss:0.5689157969176084
epoch:33,w1:1.4261325132930935,w2:0.9103846964585651,bias:-0.7852192521531431,loss:0.5680658029021554
epoch:34,w1:1.4429644377644546,w2:0.9148841324125057,bias:-0.7960147903606164,loss:0.5672214340618732
epoch:35,w1:1.459778863449434,w2:0.9193228543732863,bias:-0.8067356907792199,loss:0.5663826033121632
epoch:36,w1:1.4765747884128688,w2:0.9237005497870713,bias:-0.8173846860971365,loss:0.5655492266957719
epoch:37,w1:1.49335137062756,w2:0.9280171795109788,bias:-0.8279641285550979,loss:0.5647212230159951
epoch:38,w1:1.5101078973951256,w2:0.9322729204210061,bias:-0.8384760622625229,loss:0.5638985135760856
epoch:39,w1:1.5268437607847825,w2:0.9364681193916735,bias:-0.8489222812973116,loss:0.5630810219880366
epoch:40,w1:1.5435584379010596,w2:0.940603256401598,bias:-0.8593043763961407,loss:0.5622686740269451
epoch:41,w1:1.560251475026571,w2:0.9446789149628219,bias:-0.8696237724874015,loss:0.561461397515557
epoch:42,w1:1.5769224748746342,w2:0.94869575842781,bias:-0.8798817588737683,loss:0.5606591222290244
epoch:43,w1:1.593571086337882,w2:0.9526545110137815,bias:-0.8900795135142047,loss:0.5598617798134142
epoch:44,w1:1.6101969962404223,w2:0.9565559426133181,bias:-0.9002181225686771,loss:0.5590693037137617
epoch:45,w1:1.6267999226984742,w2:0.9604008566441293,bias:-0.9102985961389792,loss:0.5582816291089292
epoch:46,w1:1.6433796097725075,w2:0.9641900803384228,bias:-0.9203218809546884,loss:0.5574986928514801
epoch:47,w1:1.6599358231565549,w2:0.9679244569907022,bias:-0.9302888706053631,loss:0.5567204334113844
epoch:48,w1:1.6764683467005954,w2:0.9716048397777879,bias:-0.9402004138014451,loss:0.5559467908227731
epoch:49,w1:1.6929769796022147,w2:0.9752320868410456,bias:-0.9500573210511356,loss:0.555177706633214
epoch:50,w1:1.709461534136061,w2:0.9788070573819416,bias:-0.9598603700641541,loss:0.5544131238551514
epoch:51,w1:1.7259218338155558,w2:0.9823306085710964,bias:-0.9696103101320064,loss:0.5536529869192577
epoch:52,w1:1.742357711902116,w2:0.9858035931103728,bias:-0.9793078656852189,loss:0.5528972416295197
epoch:53,w1:1.7587690101938447,w2:0.9892268573191305,bias:-0.9889537391885337,loss:0.5521458351199265
epoch:54,w1:1.7751555780390362,w2:0.9926012396411381,bias:-0.9985486135033841,loss:0.5513987158126592
epoch:55,w1:1.7915172715306042,w2:0.9959275694889907,bias:-1.0080931538215423,loss:0.5506558333776981
epoch:56,w1:1.8078539528461623,w2:0.9992066663592316,bias:-1.017588009253419,loss:0.5499171386937871
epoch:57,w1:1.824165489705423,w2:1.002439339164497,bias:-1.027033814138101,loss:0.5491825838106912
epoch:58,w1:1.8404517549221389,w2:1.00562638573955,bias:-1.0364311891290499,loss:0.5484521219127004
epoch:59,w1:1.8567126260322857,w2:1.0087685924865333,bias:-1.0457807420988139,loss:0.5477257072833347
epoch:60,w1:1.872947984983764,w2:1.0118667341315752,bias:-1.055083068897607,loss:0.5470032952712022
epoch:61,w1:1.88915771787579,w2:1.0149215735703498,bias:-1.0643387539937903,loss:0.5462848422569789
epoch:62,w1:1.9053417147384553,w2:1.0179338617845812,bias:-1.0735483710188058,loss:0.5455703056214648
epoch:63,w1:1.921499869344798,w2:1.0209043378150156,bias:-1.0827124832347057,loss:0.5448596437146851
epoch:64,w1:1.9376320790492232,w2:1.023833728779221,bias:-1.0918316439388795,loss:0.5441528158259998
epoch:65,w1:1.9537382446473128,w2:1.0267227499248572,bias:-1.1009063968177337,loss:0.5434497821551901
epoch:66,w1:1.9698182702530318,w2:1.0295721047108906,bias:-1.1099372762587887,loss:0.5427505037844887
epoch:67,w1:1.985872063190113,w2:1.032382484910707,bias:-1.1189248076288183,loss:0.5420549426515223
epoch:68,w1:2.00189953389503,w2:1.035154570732262,bias:-1.1278695075241751,loss:0.5413630615231404
epoch:69,w1:2.017900595829467,w2:1.037889030951359,bias:-1.1367718839982555,loss:0.5406748239700963
epoch:70,w1:2.0338751654006053,w2:1.0405865230549218,bias:-1.1456324367700979,loss:0.5399901943425552
epoch:71,w1:2.049823161887859,w2:1.0432476933917367,bias:-1.15445165741734,loss:0.5393091377464055
epoch:72,w1:2.065744507374971,w2:1.0458731773286458,bias:-1.1632300295561369,loss:0.53863162002034
epoch:73,w1:2.081639126686576,w2:1.0484635994105658,bias:-1.1719680290101437,loss:0.5379576077136877
epoch:74,w1:2.0975069473285153,w2:1.0510195735230374,bias:-1.1806661239702676,loss:0.5372870680649698
epoch:75,w1:2.1133478994313237,w2:1.0535417030562626,bias:-1.189324775146562,loss:0.5366199689811573
epoch:76,w1:2.129161915696416,w2:1.056030581069799,bias:-1.1979444359133868,loss:0.5359562790176028
epoch:77,w1:2.144948931344592,w2:1.058486790457253,bias:-1.206525552448735,loss:0.5352959673586317
epoch:78,w1:2.1607088840665503,w2:1.0609109041104414,bias:-1.2150685638684697,loss:0.5346390037987655
epoch:79,w1:2.1764417139751546,w2:1.0633034850826064,bias:-1.223573902356069,loss:0.5339853587245575
epoch:80,w1:2.1921473635592523,w2:1.0656650867503554,bias:-1.2320419932883717,loss:0.5333350030970236
epoch:81,w1:2.207825777638869,w2:1.0679962529740665,bias:-1.2404732553577265,loss:0.5326879084346451
epoch:82,w1:2.2234769033216466,w2:1.0702975182565604,bias:-1.2488681006908755,loss:0.5320440467969255
epoch:83,w1:2.2391006899604067,w2:1.0725694078998824,bias:-1.2572269349648464,loss:0.5314033907684873
epoch:84,w1:2.2546970891117457,w2:1.0748124381600785,bias:-1.2655501575200776,loss:0.5307659134436827
epoch:85,w1:2.2702660544955866,w2:1.0770271163998768,bias:-1.2738381614709688,loss:0.5301315884117103
epoch:86,w1:2.2858075419556143,w2:1.0792139412392108,bias:-1.282091333814012,loss:0.5295003897422134
epoch:87,w1:2.3013215094205477,w2:1.0813734027035402,bias:-1.2903100555336393,loss:0.5288722919713507
epoch:88,w1:2.316807916866196,w2:1.0835059823699416,bias:-1.2984947017058996,loss:0.5282472700883181
epoch:89,w1:2.332266726278263,w2:1.0856121535109502,bias:-1.3066456416000634,loss:0.5276252995223105
epoch:90,w1:2.3476979016158626,w2:1.0876923812361505,bias:-1.3147632387782378,loss:0.5270063561299078
epoch:91,w1:2.363101408775718,w2:1.089747122631513,bias:-1.322847851193068,loss:0.5263904161828697
epoch:92,w1:2.378477215557018,w2:1.0917768268964883,bias:-1.3308998312835885,loss:0.5257774563563301
epoch:93,w1:2.3938252916269085,w2:1.0937819354788716,bias:-1.3389195260692826,loss:0.525167453717371
epoch:94,w1:2.409145608486595,w2:1.0957628822074545,bias:-1.3469072772424007,loss:0.5245603857139702
epoch:95,w1:2.4244381394380463,w2:1.097720093422485,bias:-1.354863421258588,loss:0.5239562301643076
epoch:96,w1:2.439702859551273,w2:1.0996539881039582,bias:-1.3627882894258598,loss:0.5233549652464151
epoch:97,w1:2.454939745632171,w2:1.1015649779977639,bias:-1.3706822079919698,loss:0.5227565694881658
epoch:98,w1:2.47014877619092,w2:1.1034534677397179,bias:-1.3785454982302034,loss:0.5221610217575839
epoch:99,w1:2.485329931410912,w2:1.1053198549775032,bias:-1.3863784765236349,loss:0.5215683012534701
epoch:100,w1:2.5004831931182125,w2:1.1071645304905515,bias:-1.394181454447879,loss:0.5209783874963289
epoch:101,w1:2.5156085447515317,w2:1.1089878783078941,bias:-1.4019547388523699,loss:0.5203912603195894
epoch:102,w1:2.5307059713327003,w2:1.1107902758240102,bias:-1.4096986319401947,loss:0.5198068998611086
epoch:103,w1:2.5457754594376376,w2:1.1125720939127053,bias:-1.417413431346515,loss:0.5192252865549494
epoch:104,w1:2.560816997167806,w2:1.114333697039047,bias:-1.4250994302155982,loss:0.518646401123423
epoch:105,w1:2.575830574122135,w2:1.1160754433693907,bias:-1.4327569172764896,loss:0.5180702245693868
epoch:106,w1:2.590816181369413,w2:1.117797684879524,bias:-1.4403861769173503,loss:0.5174967381687904
epoch:107,w1:2.6057738114211366,w2:1.1195007674609592,bias:-1.4479874892584839,loss:0.516925923463461
epoch:108,w1:2.620703458204803,w2:1.1211850310254061,bias:-1.455561130224079,loss:0.5163577622541196
epoch:109,w1:2.635605117037648,w2:1.1228508096074514,bias:-1.4631073716126899,loss:0.515792236593621
epoch:110,w1:2.6504787846008107,w2:1.1244984314654762,bias:-1.4706264811664793,loss:0.5152293287804104
epoch:111,w1:2.665324458913925,w2:1.1261282191808402,bias:-1.4781187226392454,loss:0.5146690213521888
epoch:112,w1:2.680142139310128,w2:1.1277404897553602,bias:-1.485584355863255,loss:0.514111297079781
epoch:113,w1:2.6949318264114743,w2:1.129335554707114,bias:-1.4930236368149066,loss:0.5135561389611977
epoch:114,w1:2.709693522104756,w2:1.1309137201645934,bias:-1.5004368176792409,loss:0.5130035302158892
epoch:115,w1:2.724427229517716,w2:1.1324752869592372,bias:-1.507824146913324,loss:0.5124534542791778
epoch:116,w1:2.739132952995649,w2:1.1340205507163719,bias:-1.51518586930852,loss:0.5119058947968721
epoch:117,w1:2.7538106980783863,w2:1.1355498019445835,bias:-1.5225222260516758,loss:0.5113608356200472
epoch:118,w1:2.7684604714776517,w2:1.1370633261235508,bias:-1.529833454785235,loss:0.5108182607999925
epoch:119,w1:2.78308228105479,w2:1.1385614037903637,bias:-1.5371197896663036,loss:0.5102781545833193
epoch:120,w1:2.7976761357988553,w2:1.1400443106243539,bias:-1.544381461424682,loss:0.5097405014072215
epoch:121,w1:2.812242045805058,w2:1.1415123175304616,bias:-1.5516186974198873,loss:0.5092052858948871
epoch:122,w1:2.8267800222535575,w2:1.1429656907211658,bias:-1.5588317216971783,loss:0.5086724928510521
epoch:123,w1:2.841290077388605,w2:1.1444046917970003,bias:-1.5660207550426057,loss:0.5081421072576964
epoch:124,w1:2.855772224498021,w2:1.1458295778256804,bias:-1.5731860150371033,loss:0.5076141142698719
epoch:125,w1:2.870226477893006,w2:1.1472406014198653,bias:-1.5803277161096358,loss:0.5070884992116637
epoch:126,w1:2.8846528528882796,w2:1.1486380108135774,bias:-1.5874460695894235,loss:0.5065652475722751
epoch:127,w1:2.899051365782543,w2:1.1500220499373046,bias:-1.5945412837572572,loss:0.5060443450022362
epoch:128,w1:2.9134220338392542,w2:1.1513929584918057,bias:-1.6016135638959228,loss:0.5055257773097298
epoch:129,w1:2.927764875267718,w2:1.1527509720206417,bias:-1.6086631123397472,loss:0.5050095304570313
epoch:130,w1:2.9420799092044816,w2:1.154096321981457,bias:-1.615690128523287,loss:0.5044955905570588
epoch:131,w1:2.9563671556950295,w2:1.1554292358160296,bias:-1.6226948090291688,loss:0.5039839438700306
epoch:132,w1:2.970626635675778,w2:1.1567499370191126,bias:-1.6296773476351034,loss:0.5034745768002241
epoch:133,w1:2.9848583709563585,w2:1.1580586452060886,bias:-1.6366379353600815,loss:0.5029674758928363
epoch:134,w1:2.999062384202189,w2:1.1593555761794567,bias:-1.6435767605097718,loss:0.5024626278309396
epoch:135,w1:3.013238698917326,w2:1.160640941994173,bias:-1.6504940087211306,loss:0.5019600194325311
epoch:136,w1:3.027387339427597,w2:1.1619149510218625,bias:-1.6573898630062418,loss:0.5014596376476714
epoch:137,w1:3.041508330864003,w2:1.1631778080139263,bias:-1.664264503795396,loss:0.5009614695557126
epoch:138,w1:3.0556016991463903,w2:1.164429714163558,bias:-1.6711181089794278,loss:0.5004655023626072
epoch:139,w1:3.0696674709673877,w2:1.1656708671666927,bias:-1.6779508539513188,loss:0.49997172339830237
epoch:140,w1:3.083705673776603,w2:1.166901461281904,bias:-1.6847629116470846,loss:0.49948012011420945
epoch:141,w1:3.097716335765076,w2:1.1681216873892695,bias:-1.6915544525859543,loss:0.4989906800807526
epoch:142,w1:3.1116994858499805,w2:1.1693317330482211,bias:-1.698325644909859,loss:0.4985033909849891
epoch:143,w1:3.1256551536595785,w2:1.1705317825544,bias:-1.7050766544222373,loss:0.49801824062830247
epoch:144,w1:3.139583369518414,w2:1.1717220169955294,bias:-1.711807644626175,loss:0.4975352169241632
epoch:145,w1:3.15348416443275,w2:1.1729026143063284,bias:-1.7185187767618857,loss:0.4970543078959573
epoch:146,w1:3.167357570076238,w2:1.1740737493224769,bias:-1.725210209843548,loss:0.4965755016748782
epoch:147,w1:3.181203618775825,w2:1.1752355938336538,bias:-1.731882100695509,loss:0.49609878649788225
epoch:148,w1:3.1950223434978815,w2:1.176388316635661,bias:-1.7385346039878646,loss:0.4956241507057037
epoch:149,w1:3.2088137778345636,w2:1.1775320835816503,bias:-1.7451678722714306,loss:0.49515158274092846
epoch:150,w1:3.222577955990388,w2:1.1786670576324696,bias:-1.7517820560121107,loss:0.49468107114612336
epoch:151,w1:3.236314912769031,w2:1.179793398906142,bias:-1.7583773036246777,loss:0.4942126045620215
epoch:152,w1:3.25002468356034,w2:1.1809112647264948,bias:-1.764953761505974,loss:0.49374617172575946
epoch:153,w1:3.263707304327554,w2:1.182020809670951,bias:-1.7715115740675431,loss:0.4932817614691652
epoch:154,w1:3.2773628115947346,w2:1.1831221856175014,bias:-1.7780508837677027,loss:0.49281936271709664
epoch:155,w1:3.290991242434402,w2:1.1842155417908666,bias:-1.7845718311430687,loss:0.49235896448582606
epoch:156,w1:3.3045926344553695,w2:1.1853010248078681,bias:-1.7910745548395397,loss:0.4919005558814736
epoch:157,w1:3.3181670257907787,w2:1.1863787787220186,bias:-1.7975591916427527,loss:0.4914441260984819
epoch:158,w1:3.3317144550863276,w2:1.1874489450673462,bias:-1.8040258765080166,loss:0.4909896644181368
epoch:159,w1:3.345234961488693,w2:1.1885116629014676,bias:-1.8104747425897372,loss:0.4905371602071291
epoch:160,w1:3.3587285846341413,w2:1.1895670688479203,bias:-1.8169059212703371,loss:0.4900866029161556
epoch:161,w1:3.3721953646373217,w2:1.1906152971377688,bias:-1.823319542188685,loss:0.4896379820785613
epoch:162,w1:3.38563534208025,w2:1.191656479650497,bias:-1.8297157332680385,loss:0.48919128730901795
epoch:163,w1:3.399048558001465,w2:1.1926907459541984,bias:-1.8360946207435118,loss:0.48874650830223954
epoch:164,w1:3.4124350538853676,w2:1.1937182233450783,bias:-1.8424563291890756,loss:0.4883036348317335
epoch:165,w1:3.4257948716517324,w2:1.1947390368862767,bias:-1.8488009815440976,loss:0.4878626567485869
epoch:166,w1:3.439128053645391,w2:1.195753309446028,bias:-1.8551286991394313,loss:0.48742356398028375
epoch:167,w1:3.4524346426260863,w2:1.1967611617351643,bias:-1.861439601723062,loss:0.48698634652955664
epoch:168,w1:3.4657146817584925,w2:1.1977627123439785,bias:-1.8677338074853171,loss:0.4865509944732681
epoch:169,w1:3.4789682146023986,w2:1.198758077778453,bias:-1.8740114330836475,loss:0.48611749796132303
epoch:170,w1:3.4921952851030547,w2:1.1997473724958714,bias:-1.88027259366699,loss:0.4856858472156091
epoch:171,w1:3.505395937581677,w2:1.200730708939817,bias:-1.8865174028997156,loss:0.4852560325289652
epoch:172,w1:3.518570216726109,w2:1.2017081975745747,bias:-1.8927459729851723,loss:0.48482804426417997
epoch:173,w1:3.5317181675816376,w2:1.2026799469189433,bias:-1.8989584146888296,loss:0.4844018728530117
epoch:174,w1:3.54483983554196,w2:1.2036460635794688,bias:-1.9051548373610303,loss:0.483977508795239
epoch:175,w1:3.557935266340302,w2:1.2046066522831096,bias:-1.9113353489593585,loss:0.4835549426577319
epoch:176,w1:3.5710045060406794,w2:1.2055618159093433,bias:-1.9175000560706288,loss:0.48313416507355006
epoch:177,w1:3.5840476010293103,w2:1.2065116555217241,bias:-1.9236490639325041,loss:0.4827151667410611
epoch:178,w1:3.5970645980061646,w2:1.2074562703989011,bias:-1.9297824764547484,loss:0.48229793842308516
epoch:179,w1:3.6100555439766566,w2:1.2083957580651066,bias:-1.9359003962401211,loss:0.48188247094605663
epoch:180,w1:3.623020486243476,w2:1.2093302143201223,bias:-1.9420029246049186,loss:0.481468755199211
epoch:181,w1:3.635959472398554,w2:1.2102597332687357,bias:-1.9480901615991701,loss:0.4810567821337889
epoch:182,w1:3.6488725503151644,w2:1.2111844073496913,bias:-1.9541622060264927,loss:0.4806465427622614
epoch:183,w1:3.661759768140154,w2:1.2121043273641492,bias:-1.9602191554636124,loss:0.4802380281575747
epoch:184,w1:3.674621174286309,w2:1.2130195825036563,bias:-1.9662611062795567,loss:0.47983122945241197
epoch:185,w1:3.6874568174248417,w2:1.2139302603776416,bias:-1.9722881536545247,loss:0.47942613783847304
epoch:186,w1:3.700266746478009,w2:1.2148364470404414,bias:-1.9783003915984394,loss:0.47902274456577365
epoch:187,w1:3.7130510106118524,w2:1.2157382270178638,bias:-1.9842979129691891,loss:0.4786210409419583
epoch:188,w1:3.7258096592290615,w2:1.2166356833333,bias:-1.9902808094905622,loss:0.4782210183316313
epoch:189,w1:3.738542741961955,w2:1.2175288975333907,bias:-1.996249171769881,loss:0.4778226681557029
epoch:190,w1:3.751250308665583,w2:1.2184179497132537,bias:-2.0022030893153406,loss:0.477425981890751
epoch:191,w1:3.7639324094109456,w2:1.2193029185412836,bias:-2.0081426505530566,loss:0.4770309510683969
epoch:192,w1:3.7765890944783247,w2:1.2201838812835273,bias:-2.014067942843827,loss:0.47663756727469586
epoch:193,w1:3.7892204143507286,w2:1.2210609138276443,bias:-2.019979052499614,loss:0.4762458221495411
epoch:194,w1:3.801826419707451,w2:1.2219340907064593,bias:-2.025876064799752,loss:0.4758557073860823
epoch:195,w1:3.8144071614177366,w2:1.2228034851211138,bias:-2.03175906400688,loss:0.4754672147301546

(np.float64(4.239223037614316),
 np.float64(1.2513317462202243),
 np.float64(-2.2294236940715884))

In [43]:
coef,intercept

(array([[5.942501 ],
        [1.3994231]], dtype=float32),
 array([-3.041245], dtype=float32))

In [44]:
custommodel=myNN()
custommodel.fit(x_train_scaled,y_train,epochs=500,loss_threshold=0.4631)

epoch:0,w1:0.9899044631276738,w2:0.9569405919425348,bias:-0.07899372792977674,loss:0.645879853336323
epoch:50,w1:1.709461534136061,w2:0.9788070573819416,bias:-0.9598603700641541,loss:0.5544131238551514
epoch:100,w1:2.5004831931182125,w2:1.1071645304905515,bias:-1.394181454447879,loss:0.5209783874963289
epoch:150,w1:3.222577955990388,w2:1.1786670576324696,bias:-1.7517820560121107,loss:0.49468107114612336
epoch:200,w1:3.8769337082171416,w2:1.2270961918891738,bias:-2.0609667436236645,loss:0.47354879778661074

In [45]:
coef,intercept

(array([[5.942501 ],
        [1.3994231]], dtype=float32),
 array([-3.041245], dtype=float32))

In [46]:
custommodel.predict(x_test_scaled)

13    0.268932
4     0.725508
1     0.236924
10    0.446448
27    0.725508
12    0.252592
dtype: float64

In [47]:
model.predict(x_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step

array([[0.2111646 ],
       [0.7487071 ],
       [0.17427608],
       [0.36073586],
       [0.7487071 ],
       [0.19204609]], dtype=float32)