<a href="https://colab.research.google.com/github/ADITI9981/Deep_Learning/blob/main/sports_and_outdoors_reviews(Word2Vec_gensim).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import gensim
import pandas as pd

In [5]:
import json
data = []

with open("Sports_and_Outdoors_5.json", "r") as f:
    for line in f:
        try:
            data.append(json.loads(line))
        except json.JSONDecodeError as e:
            print(f"Skipping bad line: {e}")

df = pd.DataFrame(data)
df.head()

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
0,AIXZKN4ACSKI,1881509818,David Briner,"[0, 0]",This came in on time and I am veru happy with ...,5.0,Woks very good,1390694400,"01 26, 2014"
1,A1L5P841VIO02V,1881509818,Jason A. Kramer,"[1, 1]",I had a factory Glock tool that I was using fo...,5.0,Works as well as the factory tool,1328140800,"02 2, 2012"
2,AB2W04NI4OEAD,1881509818,J. Fernald,"[2, 2]",If you don't have a 3/32 punch or would like t...,4.0,"It's a punch, that's all.",1330387200,"02 28, 2012"
3,A148SVSWKTJKU6,1881509818,"Jusitn A. Watts ""Maverick9614""","[0, 0]",This works no better than any 3/32 punch you w...,4.0,It's a punch with a Glock logo.,1328400000,"02 5, 2012"
4,AAAWJ6LW9WMOO,1881509818,Material Man,"[0, 0]",I purchased this thinking maybe I need a speci...,4.0,"Ok,tool does what a regular punch does.",1366675200,"04 23, 2013"

In [6]:
df.shape

(296337, 9)

In [7]:
df.reviewText[0]

'This came in on time and I am veru happy with it, I haved used it already and it makes taking out the pins in my glock 32 very easy'

In [8]:
review_text = df.reviewText.apply(gensim.utils.simple_preprocess)
review_text

0         [this, came, in, on, time, and, am, veru, happ...
1         [had, factory, glock, tool, that, was, using, ...
2         [if, you, don, have, punch, or, would, like, t...
3         [this, works, no, better, than, any, punch, yo...
4         [purchased, this, thinking, maybe, need, speci...
                                ...
296332    [this, is, water, bottle, done, right, it, is,...
296333    [if, you, re, looking, for, an, insulated, wat...
296334    [this, hydracentials, sporty, oz, double, insu...
296335    [as, usual, received, this, item, free, in, ex...
296336    [hydracentials, insulated, oz, water, bottle, ...
Name: reviewText, Length: 296337, dtype: object

In [9]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2,
    workers=4
)

In [10]:
model.build_vocab(review_text, progress_per=1000)

In [11]:
model.train(review_text,total_examples=model.corpus_count,epochs=model.epochs)

(91337845, 121496535)

In [12]:
model.save("./word2vec-sports-and-outdoors-reviews.model")

In [14]:
model.wv.most_similar("awful")

[('horrible', 0.6794429421424866),
 ('terrible', 0.6540396213531494),
 ('overpowering', 0.6504417061805725),
 ('ugly', 0.6155005097389221),
 ('horrendous', 0.5966722965240479),
 ('unpleasant', 0.5894287824630737),
 ('anomaly', 0.5709616541862488),
 ('funny', 0.5700688362121582),
 ('overwhelming', 0.5659427642822266),
 ('impossibility', 0.553417444229126)]

In [15]:
model.wv.similarity(w1="good",w2="great")

0.78871655

In [16]:
model.wv.similarity(w1="slow",w2="steady")

0.36866602